<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\Icons\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\Background.png" />
    <None Remove="Assets\Icons\icon.ico" />
    <None Remove="sqllite3\sqlite3.exe" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sqllite3\sqlite3.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Icons\icon.ico" />
    <Resource Include="Assets\Images\Background.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Icons\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
  </ItemGroup>

</Project>
